### ISSUE TITLE
Status of A8K in Upstream

### ISSUE THREAD

**Issue by jan-kiszka** [MarvellEmbeddedProcessors/atf-marvell#15]
Similar question as for the A3700: I see ATF 1.6 reporting the addition of Armada 8K support. Does it mean this repo is obsolete for that SoC and specifically the MACCHIATObin?

We need all the latest and greatest Spectre mitigations for the A72, and I would expect to find them for sure in upstream ATF.

**Comment by kostapr** [comment]
This repo includes more boards that were submitted to the mainstream. It may also include some private changes not suitable for the mainstream. I would recommend you to check if current mainstream code fully fits your needs. If it is, you can safely switch to it. Our target is to port everything we have upstream. However this repo may occasionally have more recent code.

**Comment by jan-kiszka** [comment]
Understood that it may contain more BSP (while lacking latest upstream features). That's why I'm specifically mentioning the MACCHIATObin. Is that one fully covered already?

**Comment by kostapr** [comment]
As far as I know - yes, Macchiatobin is fully covered in the upstream TF-A code.

**Comment by jan-kiszka** [comment]
Confirmed: I'm now all on upstream with U-Boot and ATF, and the board starts nicely via distro boot.

FWIW, here is Debian (ad-hoc) packaging and automated SD card image generation for the MACCHIATObin: https://github.com/siemens/jailhouse-images/tree/next.
