### ISSUE TITLE
error on lib/psci/psci_common.c during build for SolidRun Macchiatobin board with crosstool-NG

### ISSUE THREAD

**Issue by czka** [MarvellEmbeddedProcessors/atf-marvell#19]
Cross-compiling on x86_64 Arch Linux from branch `atf-v1.5-armada-18.12` (the newest one, haven't tried other branches) I get a similar error to the one described in https://github.com/ARM-software/tf-issues/issues/347.

I'm using [buildroot](https://github.com/buildroot/buildroot) checked out at tag `2020.11` with [crosstool-NG](https://archlinuxarm.org/builder/xtools/x-tools8.tar.xz). During `make` it clones https://github.com/MarvellEmbeddedProcessors/atf-marvell.git and builds it from branch `atf-v1.5-armada-18.12`, to fail as follows:

`git checkout 2020.11`
`make solidrun_macchiatobin_defconfig`
`make`
```
(...)
  CC      lib/psci/psci_mem_protect.c
lib/psci/psci_common.c: In function 'psci_do_state_coordination':
lib/psci/psci_common.c:444:3: error: array subscript 2 is above array bounds of 'plat_local_state_t[2]' {aka 'unsigned char[2]'} [-Werror=array-bounds]
  444 |   psci_set_req_local_pwr_state(lvl, cpu_idx,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  445 |           state_info->pwr_domain_state[lvl]);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from include/plat/common/platform.h:10,
                 from lib/psci/psci_common.c:14:
include/lib/psci/psci.h:253:21: note: while referencing 'pwr_domain_state'
  253 |  plat_local_state_t pwr_domain_state[PLAT_MAX_PWR_LVL + U(1)];
      |                     ^~~~~~~~~~~~~~~~
lib/psci/psci_common.c:446:31: error: array subscript 2 is above array bounds of 'plat_local_state_t[2]' {aka 'unsigned char[2]'} [-Werror=array-bounds]
  446 |   state_info->pwr_domain_state[lvl] = PSCI_LOCAL_STATE_RUN;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
In file included from include/plat/common/platform.h:10,
                 from lib/psci/psci_common.c:14:
include/lib/psci/psci.h:253:21: note: while referencing 'pwr_domain_state'
  253 |  plat_local_state_t pwr_domain_state[PLAT_MAX_PWR_LVL + U(1)];
      |                     ^~~~~~~~~~~~~~~~
  CC      lib/locks/bakery/bakery_lock_normal.c
cc1: all warnings being treated as errors
make[1]: *** [Makefile:629: build/a80x0_mcbin/release/bl31/psci_common.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/user/tmp/buildroot/output/build/arm-trusted-firmware-9484123bfe29011ed44b717a23eb53a70b97ce3d'
make: *** [package/pkg-generic.mk:250: /home/user/tmp/buildroot/output/build/arm-trusted-firmware-9484123bfe29011ed44b717a23eb53a70b97ce3d/.stamp_built] Error 2
```

This doesn't happen with the buildroot's internal toolchain, but `crosstool-NG` is an [external toolchain buildroot officially supports](https://buildroot.org/downloads/manual/manual.html#_cross_compilation_toolchain) and [recommended by Arch Linux ARM](https://archlinuxarm.org/wiki/Distcc_Cross-Compiling).

PS.
If you encounter an error like
```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here`
```
you can work around it with `sed -i 's/^YYLTYPE yylloc;$/extern YYLTYPE yylloc;/' ./output/build/uboot-2020.01/scripts/dtc/dtc-lexer.l` and running `make` again.

**Comment by freedow2000** [comment]
I have also encountered this problem，you can add
`if(lvl > PLAT_MAX_PWR_LVL){break;}`
to fix if

**Comment by pali** [comment]
This is old version of ARM trusted firmware version 1.5. You should look at the latest version 2.5. See build instructions:
https://trustedfirmware-a.readthedocs.io/en/latest/plat/marvell/armada/build.html

**Comment by czka** [comment]
After a long time I'm again trying to build a fresh `flash-image.bin` for MACCHIATObin Single Shot, on Arch Linux x86_64, this time according to the current docs @pali pointed me at (thanks!).

Close, but no cigar. TF-A build fails with `error: array subscript 0 is outside array bounds of 'volatile uint64_t[0]' {aka 'volatile long unsigned int[]'}` in `trusted-firmware-a/include/lib/mmio.h`. If anybody's interested details are in my TF-A ticket: https://developer.trustedfirmware.org/T1020
