### ISSUE TITLE
arm-trusted-firmware 1.4

### ISSUE THREAD

**Issue by cz172638** [MarvellEmbeddedProcessors/atf-marvell#4]
as arm released new version, will be any update on marvell side?

**Comment by haklai** [comment]
Hi,

Sure. we have already started the porting and validation process. Should be available by Feb 2018. In case you need it earlier we can provide patches for evaluation.

**Comment by cz172638** [comment]
are there any plans to upstream it to arm's atf?

**Comment by nullr0ute** [comment]
There's 1.5 released upstream by ARM now with spectre/meltdown fixes for affected ARM cores (A57/72)

**Comment by kostapr** [comment]
Included in Marvell ATF 1.4 release armada-18.05

**Comment by nullr0ute** [comment]
There doesn't appear to be a atf 1.4 / armada-18.05 branch/tag here yet

**Comment by kostapr** [comment]
Correct. It should be released soon.
