### ISSUE TITLE
atf-v1.3-armada-17.10 fails build gcc 5.4.0 

### ISSUE THREAD

**Issue by multiflexi** [MarvellEmbeddedProcessors/atf-marvell#6]
When following [these instruction](http://wiki.macchiatobin.net/tiki-index.php?page=Build+from+source+-+Bootloader ) atf fails build on Ubuntu 16.04.3 with
```
 DEPS    build/a80x0_mcbin/release/bl31/marvell_helpers.d
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
  DEPS    build/a80x0_mcbin/release/bl31/16550_console.d
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
  DEPS    build/a80x0_mcbin/release/bl31/console.d
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
  DEPS    build/a80x0_mcbin/release/bl31/platform_helpers.d
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
 ....
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
gcc: error: unrecognized command line option ‘-mstrict-align’
  DEPS    build/a80x0_mcbin/release/ble/sys_info.d
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
gcc: error: unrecognized command line option ‘-mstrict-align’
Building a80x0_mcbin
  CC      plat/marvell/common/sys_info.c
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
gcc: error: unrecognized command line option ‘-mstrict-align’
Makefile:703: recipe for target 'build/a80x0_mcbin/release/ble/sys_info.o' failed
make: *** [build/a80x0_mcbin/release/ble/sys_info.o] Error 1
```

**Comment by kostapr** [comment]
Which cross-compiler is used for the build?

**Comment by kostapr** [comment]
Unless there is an issue with the specific compiler, I did not find any problem with the build instructions.
Here is my "history" output:
2465  cd /work/community/
 2466  export CROSS_COMPILE=/opt/gcc-linaro-5.4.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
 2467  git clone https://github.com/MarvellEmbeddedProcessors/u-boot-marvell
 2468  cd u-boot-marvell/
 2469  git checkout -b u-boot-2017.03-armada-17.10 origin/u-boot-2017.03-armada-17.10
 2470  pwd
 2471  make -j4
 2472  export BL33=$(pwd)/u-boot.bin
 2473  cd ../
 2474  git clone https://github.com/MarvellEmbeddedProcessors/binaries-marvell
 2475  cd binaries-marvell/
 2476  git checkout -b binaries-marvell-armada-17.10 origin/binaries-marvell-armada-17.10
 2477  export SCP_BL2=$(pwd)/mrvl_scp_bl2_8040.img
 2478  cd ..
 2479  git clone https://github.com/MarvellEmbeddedProcessors/atf-marvell.git
 2480  cd atf-marvell/
 2481  git checkout -b atf-v1.3-armada-17.10 origin/atf-v1.3-armada-17.10
 2482  cd ../
 2483  git clone https://github.com/MarvellEmbeddedProcessors/mv-ddr-marvell.git .
 2484  git checkout -b mv_ddr-armada-17.10 origin/mv_ddr-armada-17.10
 2485  cd ../atf-marvell/
 2486  make USE_COHERENT_MEM=0 LOG_LEVEL=20 MV_DDR_PATH=/work/community/mv-ddr PLAT=a80x0_mcbin all fip

**Comment by multiflexi** [comment]
~~I use 5.3-2016.05 as specified [here]( http://wiki.macchiatobin.net/tiki-index.php?page=Toolchain+Installation). I see that u use newer version. Might that be the root of problem?~~

Successful build with 5.5.0-2017.10

**Comment by kostapr** [comment]
It is strange anyway. We normally build using "gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu".
The only reason for using newer version in my test was the issue statement about 5.4.0.
